vim.opt.syntax = 'on'
vim.opt.ma = true
vim.opt.mouse = 'a'
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.tabstop = 2 -- default to 2-space tabs
vim.opt.shiftwidth = 2 -- default to 2-space tabs
vim.opt.softtabstop = 2 -- default to 2-space tabs
vim.opt.expandtab = true -- expand tabs into spaces
vim.opt.autoread = true
vim.opt.nu = true
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.scrolloff = 8 -- file will scroll to follow cursor
vim.opt.clipboard = 'unnamedplus'
vim.opt.number = true -- add line numbers to buffer
vim.opt.relativenumber = true -- make line numbers relative to current line
vim.opt.smartindent = true -- indent intelligently/automatically when possible
vim.opt.backspace = 'indent,eol,start' -- make backspace work as you'd expect
vim.opt.hidden = true
vim.opt.laststatus = 2 -- Always show statusline
vim.opt.display = "lastline" -- Show as much as possible of the last line
vim.opt.showmode = true
vim.opt.showcmd = true
vim.opt.incsearch = true
vim.opt.hlsearch = true
vim.opt.ttyfast = true
vim.opt.lazyredraw = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.report = 0
vim.opt.synmaxcol = 200
vim.opt.list = true
vim.opt.colorcolumn = '80'
vim.opt.ignorecase = true
vim.opt.smartcase = true
-- filetype plugin indent on " Load plugins according to detected filetype
vim.g.netrw_banner = 0
vim.opt.termguicolors = true
vim.opt.foldlevelstart = 99
vim.opt.listchars = "eol:↵"
vim.opt.list = true
vim.opt.swapfile = false
